version: "3.8"

services:  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-express:
      image: mongo-express
      environment:
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_BASICAUTH_USERNAME=${uid}
          - ME_CONFIG_BASICAUTH_PASSWORD=${pw}
      ports:
        - "8082:8081"

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf  